In [1]:
from imutils  import paths
import cv2
import pandas as pd

In [2]:
folders=list(range(1,59))

In [3]:
def image_transform(paths,target):
    lst=[]
    for i in paths:
        img=cv2.imread(i)
        lst.append(img.flatten())
        df=pd.DataFrame(lst)
        df['target']=target
    # print(df.shape)
    return df

In [4]:
df=pd.DataFrame()
for i in folders:
    path=list(paths.list_images(rf"D:\Data Science\DataScienceProject\vehicle_sign_prediction\Images\{i}"))
    if len(path)==0:
        continue
    df_temp=image_transform(path,i)

    df=pd.concat([df,df_temp])
    print(df.shape,i)

(201, 3073) 1
(402, 3073) 2
(603, 3073) 3
(804, 3073) 4
(1125, 3073) 5
(1326, 3073) 6
(1527, 3073) 7
(2128, 3073) 8
(2329, 3073) 9
(2530, 3073) 10
(2731, 3073) 11
(2932, 3073) 12
(3133, 3073) 13
(3334, 3073) 14
(3535, 3073) 15
(3736, 3073) 16
(3937, 3073) 17
(4138, 3073) 18
(4339, 3073) 19
(4940, 3073) 20
(5141, 3073) 21
(5342, 3073) 22
(5543, 3073) 23
(5744, 3073) 24
(5945, 3073) 25
(6146, 3073) 26
(6347, 3073) 27
(6548, 3073) 28
(6749, 3073) 29
(6950, 3073) 30
(7151, 3073) 31
(7352, 3073) 32
(7553, 3073) 33
(7754, 3073) 34
(7955, 3073) 35
(8156, 3073) 36
(8357, 3073) 37
(8558, 3073) 38
(8759, 3073) 40
(8960, 3073) 41
(9161, 3073) 42
(9362, 3073) 43
(9563, 3073) 44
(9764, 3073) 45
(9965, 3073) 46
(10109, 3073) 47
(10277, 3073) 48
(10335, 3073) 49
(10528, 3073) 50
(11128, 3073) 51
(11348, 3073) 52
(11955, 3073) 53
(12557, 3073) 54
(13173, 3073) 55
(13373, 3073) 56
(13574, 3073) 57
(13770, 3073) 58

In [ ]:
df

Empty DataFrame
Columns: []
Index: []

In [5]:
df['target'].nunique()

57

In [43]:
df_temp.shape

(201, 3073)

In [38]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,3063,3064,3065,3066,3067,3068,3069,3070,3071,target
0,121,133,137,131,141,135,143,147,138,146,...,149,145,145,149,144,144,119,120,137,1
1,255,255,255,0,0,0,0,0,0,0,...,255,255,255,255,255,255,255,255,255,1
2,31,30,225,34,35,218,28,41,207,20,...,23,35,220,24,40,210,28,36,216,1
3,0,0,0,0,0,0,255,255,255,255,...,255,255,255,255,255,255,0,0,0,1
4,203,200,237,234,230,240,255,255,248,251,...,123,121,224,3,11,203,27,35,223,1

In [6]:
df.to_csv("pixels.csv",index=False)

In [7]:
df=pd.read_csv("pixels.csv")

In [8]:
df.shape

(13770, 3073)

In [9]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,3063,3064,3065,3066,3067,3068,3069,3070,3071,target
0,121,133,137,131,141,135,143,147,138,146,...,149,145,145,149,144,144,119,120,137,1
1,255,255,255,0,0,0,0,0,0,0,...,255,255,255,255,255,255,255,255,255,1
2,31,30,225,34,35,218,28,41,207,20,...,23,35,220,24,40,210,28,36,216,1
3,0,0,0,0,0,0,255,255,255,255,...,255,255,255,255,255,255,0,0,0,1
4,203,200,237,234,230,240,255,255,248,251,...,123,121,224,3,11,203,27,35,223,1