In [1]:
import numpy as np
import pandas as pd
import sklearn
import matplotlib.pyplot as plt

In [2]:
import keras

In [3]:
df=pd.read_csv(r"..\data\pixels.csv")

In [4]:
df.shape

(13770, 3073)

In [5]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,3063,3064,3065,3066,3067,3068,3069,3070,3071,target
0,121,133,137,131,141,135,143,147,138,146,...,149,145,145,149,144,144,119,120,137,1
1,255,255,255,0,0,0,0,0,0,0,...,255,255,255,255,255,255,255,255,255,1
2,31,30,225,34,35,218,28,41,207,20,...,23,35,220,24,40,210,28,36,216,1
3,0,0,0,0,0,0,255,255,255,255,...,255,255,255,255,255,255,0,0,0,1
4,203,200,237,234,230,240,255,255,248,251,...,123,121,224,3,11,203,27,35,223,1

In [6]:
df['target'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52,
       53, 54, 55, 56, 57, 58])

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X=df.drop(columns=['target'])
y=df['target']

In [9]:
X_train,X_test,y_train,y_test=train_test_split(X,y,shuffle=True,test_size=0.2, stratify=y)

In [10]:
X_train.head()

,0,1,2,3,4,5,6,7,8,9,...,3062,3063,3064,3065,3066,3067,3068,3069,3070,3071
3891,176,173,244,251,247,252,244,252,250,246,...,217,28,39,216,22,38,213,20,25,224
11473,160,143,129,150,128,110,148,123,104,145,...,43,120,82,48,122,84,52,122,86,54
2496,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255
6199,255,255,255,255,255,255,255,255,255,255,...,255,8,8,255,20,20,255,120,120,255
2677,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,255

In [17]:
df['target'].nunique()

57

In [26]:
X_train = X_train / 255.0
X_test = X_test / 255.0

In [13]:
import numpy as np
import optuna

from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report

import keras
from keras import Sequential
from keras.layers import Dense, Dropout

In [27]:
def objective(trial):

    # Number of hidden layers
    n_layers = trial.suggest_int("n_layers", 1, 4)

    model = Sequential()

    model.add(Dense(trial.suggest_int("neurons_layer_0",32,256,step=32),
            activation="relu",
            input_shape=(X_train.shape[1],)
        )
    )

    # Additional hidden layers
    for i in range(1, n_layers):

        neurons = trial.suggest_int(
            f"neurons_layer_{i}",
            32,
            256,
            step=32
        )

        model.add(
            Dense(
                neurons,
                activation="relu"
            )
        )

        dropout = trial.suggest_float(
            f"dropout_{i}",
            0.0,
            0.5,
            step=0.1
        )

        model.add(Dropout(dropout))

    # Output layer
    model.add(
        Dense(
            59,
            activation="softmax"
        )
    )

    learning_rate = trial.suggest_float(
        "learning_rate",
        1e-4,
        1e-2,
        log=True
    )

    model.compile(
        optimizer=keras.optimizers.Adam(
            learning_rate=learning_rate
        ),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"]
    )

    batch_size = trial.suggest_categorical(
        "batch_size",
        [16, 32, 64, 128]
    )

    history = model.fit(
        X_train,
        y_train,
        validation_split=0.2,
        epochs=30,
        batch_size=batch_size,
        verbose=0
    )

    return max(history.history["val_accuracy"])

In [28]:
study = optuna.create_study(
    direction="maximize"
)

study.optimize(
    objective,
    n_trials=30
)

[I 2026-09-01 12:14:46,877] A new study created in memory with name: no-name-73fda2a2-09e4-4762-b450-e013395b4985
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 12:15:14,356] Trial 0 finished with value: 0.48865699768066406 and parameters: {'n_layers': 3, 'neurons_layer_0': 32, 'neurons_layer_1': 64, 'dropout_1': 0.30000000000000004, 'neurons_layer_2': 96, 'dropout_2': 0.5, 'learning_rate': 0.00011158735778822887, 'batch_size': 64}. Best is trial 0 with value: 0.48865699768066406.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 12:15:33,151] Trial 1 finished with value: 0.6737749576568604 and parameters: {'n_layers': 1, 'neurons_layer_0': 128, 'learning_rate': 0.0008677235075326607, 'batch_size': 128}. Best is trial 1 with value: 0.6737749576568604.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 12:16:42,190] Trial 2 finished with value: 0.7504537105560303 and parameters: {'n_layers': 2, 'neurons_layer_0': 224, 'neurons_layer_1': 160, 'dropout_1': 0.1, 'learning_rate': 0.00046531155714251885, 'batch_size': 32}. Best is trial 2 with value: 0.7504537105560303.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 12:17:54,201] Trial 3 finished with value: 0.6887477040290833 and parameters: {'n_layers': 1, 'neurons_layer_0': 256, 'learning_rate': 0.00011803536865111776, 'batch_size': 32}. Best is trial 2 with value: 0.7504537105560303.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 12:18:33,605] Trial 4 finished with value: 0.30081668496131897 and parameters: {'n_layers': 3, 'neurons_layer_0': 64, 'neurons_layer_1': 160, 'dropout_1': 0.5, 'neurons_layer_2': 128, 'dropout_2': 0.0, 'learning_rate': 0.0022540775251287354, 'batch_size': 32}. Best is trial 2 with value: 0.7504537105560303.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 12:18:51,093] Trial 5 finished with value: 0.6379310488700867 and parameters: {'n_layers': 2, 'neurons_layer_0': 64, 'neurons_layer_1': 224, 'dropout_1': 0.30000000000000004, 'learning_rate': 0.002522924514986219, 'batch_size': 128}. Best is trial 2 with value: 0.7504537105560303.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 12:19:30,309] Trial 6 finished with value: 0.7386569976806641 and parameters: {'n_layers': 3, 'neurons_layer_0': 192, 'neurons_layer_1': 256, 'dropout_1': 0.1, 'neurons_layer_2': 64, 'dropout_2': 0.2, 'learning_rate': 0.0003277398968825599, 'batch_size': 64}. Best is trial 2 with value: 0.7504537105560303.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 12:20:46,700] Trial 7 finished with value: 0.5562613606452942 and parameters: {'n_layers': 2, 'neurons_layer_0': 256, 'neurons_layer_1': 256, 'dropout_1': 0.1, 'learning_rate': 0.005697629425150904, 'batch_size': 32}. Best is trial 2 with value: 0.7504537105560303.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 12:21:10,303] Trial 8 finished with value: 0.0902903825044632 and parameters: {'n_layers': 3, 'neurons_layer_0': 160, 'neurons_layer_1': 96, 'dropout_1': 0.5, 'neurons_layer_2': 224, 'dropout_2': 0.5, 'learning_rate': 0.006085004140549034, 'batch_size': 128}. Best is trial 2 with value: 0.7504537105560303.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 12:21:38,907] Trial 9 finished with value: 0.7341197729110718 and parameters: {'n_layers': 2, 'neurons_layer_0': 256, 'neurons_layer_1': 256, 'dropout_1': 0.1, 'learning_rate': 0.0004793424316415423, 'batch_size': 128}. Best is trial 2 with value: 0.7504537105560303.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 12:23:35,332] Trial 10 finished with value: 0.7109800577163696 and parameters: {'n_layers': 4, 'neurons_layer_0': 192, 'neurons_layer_1': 160, 'dropout_1': 0.0, 'neurons_layer_2': 256, 'dropout_2': 0.2, 'neurons_layer_3': 128, 'dropout_3': 0.1, 'learning_rate': 0.0013029916533026566, 'batch_size': 16}. Best is trial 2 with value: 0.7504537105560303.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 12:24:14,840] Trial 11 finished with value: 0.667422890663147 and parameters: {'n_layers': 4, 'neurons_layer_0': 192, 'neurons_layer_1': 160, 'dropout_1': 0.2, 'neurons_layer_2': 32, 'dropout_2': 0.2, 'neurons_layer_3': 256, 'dropout_3': 0.5, 'learning_rate': 0.0003230852641241243, 'batch_size': 64}. Best is trial 2 with value: 0.7504537105560303.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 12:24:51,133] Trial 12 finished with value: 0.7427404522895813 and parameters: {'n_layers': 3, 'neurons_layer_0': 192, 'neurons_layer_1': 192, 'dropout_1': 0.0, 'neurons_layer_2': 160, 'dropout_2': 0.30000000000000004, 'learning_rate': 0.00025995267787164004, 'batch_size': 64}. Best is trial 2 with value: 0.7504537105560303.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 12:28:01,075] Trial 13 finished with value: 0.7332123517990112 and parameters: {'n_layers': 2, 'neurons_layer_0': 224, 'neurons_layer_1': 192, 'dropout_1': 0.0, 'learning_rate': 0.00022458576973287707, 'batch_size': 16}. Best is trial 2 with value: 0.7504537105560303.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 13:42:05,647] Trial 14 finished with value: 0.7368420958518982 and parameters: {'n_layers': 3, 'neurons_layer_0': 128, 'neurons_layer_1': 128, 'dropout_1': 0.0, 'neurons_layer_2': 160, 'dropout_2': 0.0, 'learning_rate': 0.0006750457219096717, 'batch_size': 32}. Best is trial 2 with value: 0.7504537105560303.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 13:42:47,069] Trial 15 finished with value: 0.7019056081771851 and parameters: {'n_layers': 2, 'neurons_layer_0': 160, 'neurons_layer_1': 96, 'dropout_1': 0.2, 'learning_rate': 0.00020406486577809345, 'batch_size': 64}. Best is trial 2 with value: 0.7504537105560303.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 13:43:25,070] Trial 16 finished with value: 0.7046279311180115 and parameters: {'n_layers': 1, 'neurons_layer_0': 224, 'learning_rate': 0.0005302741342470845, 'batch_size': 64}. Best is trial 2 with value: 0.7504537105560303.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 13:44:31,847] Trial 17 finished with value: 0.6796733140945435 and parameters: {'n_layers': 4, 'neurons_layer_0': 224, 'neurons_layer_1': 192, 'dropout_1': 0.2, 'neurons_layer_2': 192, 'dropout_2': 0.4, 'neurons_layer_3': 32, 'dropout_3': 0.0, 'learning_rate': 0.0012365002772604192, 'batch_size': 32}. Best is trial 2 with value: 0.7504537105560303.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 13:46:01,698] Trial 18 finished with value: 0.7454627752304077 and parameters: {'n_layers': 3, 'neurons_layer_0': 128, 'neurons_layer_1': 192, 'dropout_1': 0.1, 'neurons_layer_2': 160, 'dropout_2': 0.30000000000000004, 'learning_rate': 0.00019145641459384027, 'batch_size': 16}. Best is trial 2 with value: 0.7504537105560303.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 13:47:18,749] Trial 19 finished with value: 0.6442831158638 and parameters: {'n_layers': 2, 'neurons_layer_0': 96, 'neurons_layer_1': 32, 'dropout_1': 0.30000000000000004, 'learning_rate': 0.00012645500035302315, 'batch_size': 16}. Best is trial 2 with value: 0.7504537105560303.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 13:48:35,265] Trial 20 finished with value: 0.6842105388641357 and parameters: {'n_layers': 1, 'neurons_layer_0': 128, 'learning_rate': 0.00018274656901163717, 'batch_size': 16}. Best is trial 2 with value: 0.7504537105560303.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 13:50:48,237] Trial 21 finished with value: 0.754083514213562 and parameters: {'n_layers': 3, 'neurons_layer_0': 160, 'neurons_layer_1': 192, 'dropout_1': 0.1, 'neurons_layer_2': 160, 'dropout_2': 0.30000000000000004, 'learning_rate': 0.0003213819761880707, 'batch_size': 16}. Best is trial 21 with value: 0.754083514213562.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 13:52:25,127] Trial 22 finished with value: 0.7518149018287659 and parameters: {'n_layers': 3, 'neurons_layer_0': 160, 'neurons_layer_1': 224, 'dropout_1': 0.1, 'neurons_layer_2': 128, 'dropout_2': 0.30000000000000004, 'learning_rate': 0.0004002054490901507, 'batch_size': 16}. Best is trial 21 with value: 0.754083514213562.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 13:55:54,391] Trial 23 finished with value: 0.7191470265388489 and parameters: {'n_layers': 4, 'neurons_layer_0': 160, 'neurons_layer_1': 224, 'dropout_1': 0.1, 'neurons_layer_2': 96, 'dropout_2': 0.30000000000000004, 'neurons_layer_3': 256, 'dropout_3': 0.5, 'learning_rate': 0.0004038920408054473, 'batch_size': 16}. Best is trial 21 with value: 0.754083514213562.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 13:59:37,672] Trial 24 finished with value: 0.676950991153717 and parameters: {'n_layers': 3, 'neurons_layer_0': 160, 'neurons_layer_1': 224, 'dropout_1': 0.2, 'neurons_layer_2': 128, 'dropout_2': 0.4, 'learning_rate': 0.00078939741509928, 'batch_size': 16}. Best is trial 21 with value: 0.754083514213562.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 14:00:53,314] Trial 25 finished with value: 0.7109800577163696 and parameters: {'n_layers': 2, 'neurons_layer_0': 96, 'neurons_layer_1': 128, 'dropout_1': 0.1, 'learning_rate': 0.0006014759100778751, 'batch_size': 16}. Best is trial 21 with value: 0.754083514213562.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 14:02:10,128] Trial 26 finished with value: 0.7218693494796753 and parameters: {'n_layers': 4, 'neurons_layer_0': 224, 'neurons_layer_1': 224, 'dropout_1': 0.2, 'neurons_layer_2': 192, 'dropout_2': 0.1, 'neurons_layer_3': 128, 'dropout_3': 0.2, 'learning_rate': 0.0010668444139074313, 'batch_size': 32}. Best is trial 21 with value: 0.754083514213562.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 14:03:29,809] Trial 27 finished with value: 0.32622504234313965 and parameters: {'n_layers': 3, 'neurons_layer_0': 96, 'neurons_layer_1': 128, 'dropout_1': 0.0, 'neurons_layer_2': 96, 'dropout_2': 0.4, 'learning_rate': 0.001847671597869624, 'batch_size': 16}. Best is trial 21 with value: 0.754083514213562.
d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
[I 2026-09-01 14:05:13,616] Trial 28 finished with value: 0.7409256100654602 and parameters: {'n_layers': 2, 'neurons_layer_0': 192, 'neurons_layer_1': 160, 'dropout_1': 0.1, 'learning_rate': 0.0003698234587194248, 'batch_size': 16}. Best is trial 21 with value: 0.754083514213562.

In [29]:
print("Best validation accuracy:")
print(study.best_value)

print("\nBest hyperparameters:")
print(study.best_params)

Best validation accuracy:
0.754083514213562

Best hyperparameters:
{'n_layers': 3, 'neurons_layer_0': 160, 'neurons_layer_1': 192, 'dropout_1': 0.1, 'neurons_layer_2': 160, 'dropout_2': 0.30000000000000004, 'learning_rate': 0.0003213819761880707, 'batch_size': 16}

In [30]:
best = study.best_params

model = Sequential()

model.add(
    Dense(
        best["neurons_layer_0"],
        activation="relu",
        input_shape=(X_train.shape[1],)
    )
)

for i in range(1, best["n_layers"]):

    model.add(
        Dense(
            best[f"neurons_layer_{i}"],
            activation="relu"
        )
    )

    model.add(
        Dropout(best[f"dropout_{i}"])
    )

model.add(
    Dense(
        59,
        activation="softmax"
    )
)

d:\Data Science\DataScienceProject\vehicle_sign_prediction\venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [31]:
model.compile(
    optimizer=keras.optimizers.Adam(
        learning_rate=best["learning_rate"]
    ),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

In [32]:
early_stopping = keras.callbacks.EarlyStopping(
    monitor="val_loss",
    patience=5,
    restore_best_weights=True
)

In [33]:
history = model.fit(
    X_train,
    y_train,
    validation_split=0.2,
    epochs=100,
    batch_size=best["batch_size"],
    callbacks=[early_stopping],
    verbose=1
)

Epoch 1/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.1651 - loss: 3.3855 - val_accuracy: 0.2813 - val_loss: 2.6002
Epoch 2/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.3339 - loss: 2.4397 - val_accuracy: 0.4519 - val_loss: 1.9772
Epoch 3/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.4181 - loss: 2.0400 - val_accuracy: 0.5009 - val_loss: 1.7743
Epoch 4/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.4881 - loss: 1.7713 - val_accuracy: 0.5740 - val_loss: 1.5281
Epoch 5/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.5355 - loss: 1.5892 - val_accuracy: 0.5971 - val_loss: 1.4158
Epoch 6/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.5743 - loss: 1.4286 - val_accuracy: 0.6216 - val_loss: 1.3016
Epoch 7/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.6119 - loss: 1.3034 - val_accuracy: 0.6461 - val_loss: 1.2323
Epoch 8/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.6429 - loss: 1.1604 - val_accuracy: 0.6407 - val_loss: 1.2111
Epoch 9/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.6601 - loss: 1.0861 - val_accuracy: 0.6706 - val_loss: 1.0968
Epoch 10/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.6901 - loss: 0.9991 - val_accuracy: 0.6783 - val_loss: 1.0781
Epoch 11/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7059 - loss: 0.9332 - val_accuracy: 0.6611 - val_loss: 1.1563
Epoch 12/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.7152 - loss: 0.8829 - val_accuracy: 0.6729 - val_loss: 1.0567
Epoch 13/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7337 - loss: 0.8306 - val_accuracy: 0.7037 - val_loss: 0.9793
Epoch 14/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - accuracy: 0.7452 - loss: 0.7800 - val_accuracy: 0.6919 - val_loss: 1.0579
Epoch 15/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7569 - loss: 0.7289 - val_accuracy: 0.7051 - val_loss: 0.9896
Epoch 16/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7701 - loss: 0.7009 - val_accuracy: 0.7074 - val_loss: 1.0242
Epoch 17/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7763 - loss: 0.6614 - val_accuracy: 0.7119 - val_loss: 0.9937
Epoch 18/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7819 - loss: 0.6362 - val_accuracy: 0.7196 - val_loss: 0.9719
Epoch 19/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.7929 - loss: 0.6110 - val_accuracy: 0.7210 - val_loss: 0.9782
Epoch 20/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.8032 - loss: 0.5773 - val_accuracy: 0.7237 - val_loss: 0.9452
Epoch 21/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.8004 - loss: 0.5773 - val_accuracy: 0.7191 - val_loss: 0.9405
Epoch 22/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8133 - loss: 0.5429 - val_accuracy: 0.7169 - val_loss: 0.9923
Epoch 23/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8229 - loss: 0.5173 - val_accuracy: 0.7328 - val_loss: 0.9341
Epoch 24/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8248 - loss: 0.5076 - val_accuracy: 0.7400 - val_loss: 0.9618
Epoch 25/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8319 - loss: 0.4829 - val_accuracy: 0.7255 - val_loss: 0.9884
Epoch 26/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8391 - loss: 0.4667 - val_accuracy: 0.7455 - val_loss: 0.9424
Epoch 27/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8401 - loss: 0.4582 - val_accuracy: 0.7269 - val_loss: 1.0434
Epoch 28/100
551/551 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8414 - loss: 0.4498 - val_accuracy: 0.7341 - val_loss: 1.0170

In [34]:
test_loss, test_accuracy = model.evaluate(
    X_test,
    y_test,
    verbose=1
)

print("Test Loss:", test_loss)
print("Test Accuracy:", test_accuracy)

87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.7393 - loss: 0.9852
Test Loss: 0.9852256774902344
Test Accuracy: 0.739288330078125

In [35]:
y_pred_prob = model.predict(X_test)

87/87 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [36]:
y_pred = np.argmax(y_pred_prob, axis=1)

In [37]:
y_pred

array([36, 55, 51, ..., 22, 55, 48], shape=(2754,))

In [38]:
print("Actual:   ", y_test[:20])
print("Predicted:", y_pred[:20])

Actual:    8237     37
12742    55
10593    51
5097     21
10141    48
9701     45
11110    51
11253    52
8535     38
6657     29
2735     12
2551     11
11066    51
3884     17
6724     29
9128     42
6704     29
9101     42
1437      7
10265    48
Name: target, dtype: int64
Predicted: [36 55 51 21 48 45 51 52 40 12 12 11 51 17 29 42 29 42  7 48]

In [39]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)

print("Test Accuracy:", accuracy)
print("Test Accuracy %:", accuracy * 100)

Test Accuracy: 0.739288307915759
Test Accuracy %: 73.92883079157589

In [40]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.86      0.75      0.80        40
           2       0.52      0.30      0.38        40
           3       0.54      0.63      0.58        41
           4       0.86      0.90      0.88        40
           5       0.77      0.77      0.77        64
           6       0.91      0.72      0.81        40
           7       0.68      0.85      0.76        40
           8       0.85      0.83      0.84       120
           9       0.88      0.70      0.78        40
          10       0.89      0.83      0.86        41
          11       0.86      0.90      0.88        41
          12       0.69      0.82      0.75        40
          13       0.83      0.85      0.84        40
          14       0.83      0.75      0.79        40
          15       0.61      0.68      0.64        40
          16       0.63      0.65      0.64        40
          17       0.84      0.80      0.82        40
          18       0.84      0.65      0.73        40
          19       0.86      0.62      0.72        40
          20       0.63      0.93      0.76       121
          21       0.75      0.45      0.56        40
          22       0.94      0.78      0.85        40
          23       0.53      0.82      0.65        40
          24       0.46      0.15      0.23        40
          25       0.57      0.50      0.53        40
          26       0.53      0.53      0.53        40
          27       0.65      0.75      0.70        40
          28       0.68      0.70      0.69        40
          29       0.71      0.62      0.67        40
          30       0.76      0.76      0.76        41
          31       0.65      0.85      0.74        40
          32       0.77      0.60      0.68        40
          33       0.76      0.80      0.78        40
          34       0.68      0.57      0.62        40
          35       0.79      0.82      0.80        40
          36       0.41      0.60      0.48        40
          37       0.28      0.12      0.17        41
          38       0.66      0.62      0.64        40
          40       0.59      0.75      0.66        40
          41       0.57      0.60      0.59        40
          42       0.43      0.45      0.44        40
          43       0.38      0.33      0.35        40
          44       0.81      0.72      0.76        40
          45       0.77      0.68      0.72        40
          46       0.77      0.85      0.81        40
          47       0.80      0.14      0.24        29
          48       0.54      0.82      0.65        34
          49       0.64      0.58      0.61        12
          50       0.67      0.85      0.75        39
          51       0.97      0.95      0.96       120
          52       0.73      0.80      0.76        44
          53       0.95      0.96      0.96       122
          54       0.91      0.89      0.90       121
          55       0.87      0.94      0.90       123
          56       0.72      0.82      0.77        40
          57       0.84      0.65      0.73        40
          58       0.95      0.90      0.92        40

    accuracy                           0.74      2754
   macro avg       0.72      0.70      0.69      2754
weighted avg       0.74      0.74      0.73      2754

In [41]:
model.save("vehicle_sign_ann.keras")

In [43]:

df_signs = pd.read_csv(
    r"D:\Data Science\DataScienceProject\vehicle_sign_prediction\data\traffic_sign.csv"
)

In [44]:
sign_mapping = dict(
    zip(df_signs["ClassId"], df_signs["Name"])
)

In [45]:
prediction = y_pred[0]

print("Predicted Class ID:", prediction)
print("Predicted Sign:", sign_mapping[prediction])

Predicted Class ID: 36
Predicted Sign: Side road junction